### 한글 적용
GET http://localhost:9012/create-pdf?
    text={{$random.alphanumeric(8)}}

<> sample.pdf


### 텍스트 스타일 및 정렬
GET http://localhost:9012/create-styled-pdf?
    text={{$random.alphanumeric(8)}}

<> styled_sample.pdf

### 이미지, 도형
GET http://localhost:9012/create-image-pdf?
    text={{$random.alphanumeric(8)}}

<> image_sample-1.pdf


### 좌표 및 레이아웃으로 텍스트나 이미지 배치
GET http://localhost:9012/create-image-layout-pdf?
    text={{$random.alphanumeric(8)}}

<> image_sample-5.pdf



### 테이블 추가하기
GET http://localhost:9012/create-table-pdf

<> image_sample-8.pdf


### 테이블과 이미지 조합
GET http://localhost:9012/create-image-table-pdf

<> image_sample-9.pdf


### 페이지 크기, 여백 설정
GET http://localhost:9012/structured-pdf

<> structured_sample-1.pdf


### 헤더와 푸터 적용
GET http://localhost:9012/create-custom-header-footer-pdf?
    title={{$random.alphanumeric(8)}}&
    footer={{$random.alphanumeric(8)}}

<> header-footer-sample.pdf


### 문자열로 워터마크 넣기
GET http://localhost:9012/create-pdf-with-watermark?
    watermarkText={{$random.alphanumeric(8)}}

<> watermark-sample.pdf


### 동적 셀 생성 및 포맷팅
GET http://localhost:9012/create-dynamic-table-pdf?
    rows={{$random.integer(10)}}&
    cols={{$random.integer(20)}}

<> dynamic-table-sample-1.pdf







### 커스텀 배치 기본
GET http://localhost:9012/create-custom-pdf?
    text={{$random.alphanumeric(8)}}&
    templateType={{$random.alphanumeric(8)}}

<> custom-1.pdf

### 커스텀 배치 1
GET http://localhost:9012/create-custom-pdf?
    text={{$random.alphanumeric(8)}}&
    templateType=template1

<> custom-2.pdf

### 커스텀 배치 2
GET http://localhost:9012/create-custom-pdf?
    text={{$random.alphanumeric(8)}}&
    templateType=template2

<> custom-3.pdf






### 보안 설정(암호화, 권한)
GET http://localhost:9012/create-pdf-secure

<> secure-sample-2.pdf






