### 한글 적용
GET http://localhost:9012/create-pdf?
    text={{$random.alphanumeric(8)}}

<> sample.pdf


### 텍스트 스타일 및 정렬
GET http://localhost:9012/create-styled-pdf?
    text={{$random.alphanumeric(8)}}

<> styled_sample.pdf

### 이미지, 도형
GET http://localhost:9012/create-image-pdf?
    text={{$random.alphanumeric(8)}}

<> image_sample-1.pdf


### 좌표 및 레이아웃으로 텍스트나 이미지 배치
GET http://localhost:9012/create-image-layout-pdf?
    text={{$random.alphanumeric(8)}}

<> image_sample-5.pdf



### 테이블 추가하기
GET http://localhost:9012/create-table-pdf

<> image_sample-8.pdf


### 테이블과 이미지 조합
GET http://localhost:9012/create-image-table-pdf

<> image_sample-9.pdf


### 페이지 크기, 여백 설정
GET http://localhost:9012/structured-pdf

<> structured_sample-1.pdf


### 헤더와 푸터 적용
GET http://localhost:9012/create-custom-header-footer-pdf?
    title={{$random.alphanumeric(8)}}&
    footer={{$random.alphanumeric(8)}}

<> header-footer-sample.pdf